AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AliasProduction
      Action: "lambda:InvokeFunction"
      Principal: elasticloadbalancing.amazonaws.com

  #ProductionListenerRule:
  #  Type: AWS::ElasticLoadBalancingV2::ListenerRule
  #  Properties:
  #    Actions:
  #      - Type: forward
  #        TargetGroupArn: !Ref LambdaTargetGroup
  #    Conditions:
  #      - Field: path-pattern
  #        PathPatternConfig:
  #          Values:
  #            - /hola.txt
  #    ListenerArn: arn:aws:elasticloadbalancing:us-east-1:562080862179:listener/app/Kentriki01/318557fd4d1a6ad4/a214fb9369cd3a2c
  #    Priority: 1

  LambdaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: false
      Name: TargetGroupProduction
      TargetType: lambda
      Targets:
        - Id: !Ref AliasProduction

  AliasProduction:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref HelloWorldFunction
      FunctionVersion: !GetAtt Version.Version
      Name: production

  Version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref HelloWorldFunction
      Description: $LATEST

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Description: Lambda como target
      FunctionName: test-hola
      Environment:
        Variables:
          PATH: production/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
              Resource: 'arn:aws:s3:::static.test.video/*'
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn

  Version:
    Description: "Latest version for HelloWorldFunction"
    Value: !GetAtt Version.Version
    Export:
      Name: !Sub ${AWS::StackName}-FunctionVersion
